# AWSテンプレートのバージョン。存在する唯一のバージョンが下記なので実質固定。
AWSTemplateFormatVersion: 2010-09-09
# テンプレートの説明。実行時に表示されるので記載がベター。
Description: AWS-Study Template

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.midium
  AvailabilityZoneType:
    Type: CommaDelimitedList
    Default: ap-northeast-1a, ap-northeast-1c
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Default: study-aws-lesson
    Description: Select Key Pair Name.

# リソースの定義
Resources:
  # VPC定義
  StudyAwsVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: study-aws-vpc

  # EC2Instance定義
  StudyAwsEC2Instace:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref StudyAwsSubnetAZ1a
      InstanceType: !Ref InstanceType
      AvailabilityZone: !Select [0, !Ref AvailabilityZoneType]
      ImageId: ami-0d7ed3ddb85b521a6
      KeyName: !Ref KeyPair
      Monitoring: false
      InstanceInitiatedShutdownBehavior: stop
      SecurityGroupIds:
        - !Ref StudyAwsEc2SecurityGroup
      Tags:
        - Key: Name
          Value: study-aws-ec2

  # ElasticIp定義
  StudyAwsElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      Domain: 52.197.179.237
    DependsOn: StudyAwsEC2Instace

  # Subnet定義
  StudyAwsSubnetAZ1a:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/27
      VpcId: !Ref StudyAwsVPC
      AvailabilityZone: !Select [0, !Ref AvailabilityZoneType]
      Tags:
        - Key: Name
          Value: study-aws-subnet-az1

  StudyAwsSubnetAZ1c:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.32/27
      VpcId: !Ref StudyAwsVPC
#      AvailabilityZone: ap-northeast-1c
      AvailabilityZone: !Select [1, !Ref AvailabilityZoneType]
      Tags:
        - Key: Name
          Value: study-aws-subnet-az2

  # InternetGateway定義
  StudyAwsInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: study-aws-igw

  # VPCGatewayAttachment定義
  StudyAwsGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref StudyAwsVPC
      InternetGatewayId: !Ref StudyAwsInternetGateway

  # RouteTable定義
  StudyAwsRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref StudyAwsVPC
      Tags:
        - Key: Name
          Value: study-aws-route-table

  StudyAwsRouteLocal:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref StudyAwsRouteTable
      SubnetId: !Ref StudyAwsSubnetAZ1a

  StudyAwsRouteInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref StudyAwsRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref StudyAwsInternetGateway

  # SecurityGroup
  StudyAwsEc2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref StudyAwsVPC
      GroupDescription: This Security Group is for my studying of AWS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 111.239.255.229/32
      # Railsのアプリケーションサーバー用
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: aws-study-ec2-securityGroup

  StudyAwsRdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref StudyAwsVPC
      GroupDescription: Study AWS RDS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref StudyAwsEc2SecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: study-aws-securityGroup-rds

  # RDS定義
  StudyAwsRds:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: StudyAwsLesson
      Port: 3306
      DBInstanceClass: db.t2.micro
      AvailabilityZone: !Select [0, !Ref AvailabilityZoneType]
      VPCSecurityGroups:
        - !Ref StudyAwsRdsSecurityGroup
      Engine: mysql
      EngineVersion: 8.0.13
      LicenseModel: general-public-license
      DBSubnetGroupName: !Ref StudyAwsRdsSubnetGroup
      MasterUsername: root
      MasterUserPassword: password
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      StorageType: gp2
      BackupRetentionPeriod: 1
      PreferredBackupWindow: 19:00-20:00
      PreferredMaintenanceWindow: sun:10:00-sun:11:00

  StudyAwsRdsSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: This DBSubnet Group is for my studying of AWS
      SubnetIds:
        - !Ref StudyAwsSubnetAZ1a
        - !Ref StudyAwsSubnetAZ1c

  # ELB定義
  StudyAwsELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: study-aws-elb
      SecurityGroups:
        - !Ref StudyAwsEc2SecurityGroup
      Subnets:
        - !Ref StudyAwsSubnetAZ1a
        - !Ref StudyAwsSubnetAZ1c






